apiVersion: v1
kind: Service
metadata:
  name: myname
spec:
  type: NodePort
  selector:
    app: myname
  ports:
  - protocol: TCP
    port: 5000         # service port
    targetPort: 5000   # container port
    nodePort: 30007    # external port on the node
