apiVersion: apps/v1
kind: Deployment
metadata:
  name: myname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myname
  template:
    metadata:
      labels:
        app: myname
    spec:
      containers:
      - name: myname
        image: kasimbasaragi/myname:latest
        ports:
        - containerPort: 5000
